---
name: tag
on:  # yamllint disable-line rule:truthy
  push:
    branches: master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Tag
      run: |
        sudo snap install yq
        VER=$(yq r Chart.yaml 'version')
        if [[ "$VER" == "" ]]; then
          echo "Chart.yaml version not found, skipping git tag";
        if git rev-parse $VER >/dev/null 2>&1; then
          echo "tag exists, skipping git tag";
        else
          git tag $VER
          git push origin $VER
        fi
